# my experiments with python
num1 = 18
num2 = ['wow', 'i', 'can', 'count!']
num3 = num1

for i,num2 in enumerate(num2):
    print(f"{num2}")
    if num3 > 20:
        print(f"I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE I LIVE ")
    else:
        print(f"I'm only {num3}, not more than 20. Goodbye.")
        num3 += 1